package compila;
public interface ScannerConstants
{

    int[] TOKEN_STATE = { -1,   0,  15,  23,  24,  18,  22,  16,  16,  16,  10,  20,  20,  17,  20,  20,  20,  20,  20,  20,  -1,  -1,  18,  20,  20,  20,  20,  20,  20,  20,  20,  17,  20,   2,  -1,  19,  18,  20,  20,  20,  20,  20,  14,  20,  20,  20,   8,  20,  -1,  20,  20,  20,  20,  -1,  20,  20,  20,   6,  -1,  20,  20,  20,  20,  11,  20,  20,  20,  -1,  20,  20,  20,  20,  20,  13,  20,  -1,  20,  20,  20,  20,  20,   5,  -1,  20,   7,  20,  12,   9,  -1,   4,  20,  -1,  20,  -1,   3,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  21 };

    String[] SCANNER_ERROR =
    {
        "Caractere n�o esperado",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Erro identificando str",
        "Erro identificando numR",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Erro identificando str",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Erro identificando str",
        "",
        "",
        "",
        "",
        "Erro identificando ENT",
        "",
        "",
        "",
        "",
        "Erro identificando str",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Erro identificando str",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Erro identificando str",
        "",
        "",
        "",
        "",
        "",
        "",
        "Erro identificando str",
        "",
        "",
        "",
        "",
        "",
        "Erro identificando str",
        "",
        "",
        "Erro identificando str",
        "",
        "Erro identificando str",
        "",
        "Erro identificando str",
        "Erro identificando str",
        "Erro identificando str",
        "Erro identificando str",
        "Erro identificando str",
        "Erro identificando str",
        "Erro identificando str",
        ""
    };

}
